name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-lib:
    uses: ./.github/workflows/build.yml

  format-check-lib:
    uses: ./.github/workflows/format.yml

  lint-lib:
    uses: ./.github/workflows/lint.yml

  unit-test:
    uses: ./.github/workflows/test.yml

  integration-test:
    uses: ./.github/workflows/integration-test.yml