name: test

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: |
          npm i -g yarn typescript
          yarn install
      - name: Install baedeker
        uses: UniqueNetwork/baedeker-action/setup@v1-no-debug-output
        with:
          version: 'v0.1.5'
          useCache: false

      - name: Setup library
        run: mkdir -p .baedeker/vendor/ && git clone https://github.com/UniqueNetwork/baedeker-library .baedeker/vendor/baedeker-library

      - name: Pull polkadot docker image
        run: docker pull uniquenetwork/ci-unique-assethub:polkadot

      - name: Pull asset-hub docker image
        run: docker pull uniquenetwork/ci-unique-assethub:polkadot-parachain

      - name: Start network
        uses: UniqueNetwork/baedeker-action@built
        id: bdk
        with:
          jpath: |
            .baedeker/vendor
          tla-str: |
            relay_spec=rococo-local
          inputs: |
            .baedeker/multiple-assethub.jsonnet
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/polkadot':'%s/.baedeker/polkadot' % repoDir})
            snippet:(import 'baedeker-library/ops/rewrites.libsonnet').rewriteNodePaths({'bin/assethub':{dockerImage:'uniquenetwork/ci-unique-assethub:polkadot-parachain'}})
      
      - name: Setup node settings
        run: |
          tsc ./.baedeker/init_fee.ts || true
          node ./.baedeker/init_fee.js
      
      - name: Run tests
        run: |
          yarn test tests/integration